version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - .env

    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend/views:/usr/src/app/views:rw
    networks:
      - backend-network

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
