CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE games (
    id UUID PRIMARY KEY,
    creator VARCHAR(255) REFERENCES users(username) ON DELETE CASCADE NOT NULL,
    player VARCHAR(255) REFERENCES users(username) ON DELETE CASCADE DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
